### ISSUE TITLE
Waiting Time - Loading Time...

### ISSUE THREAD

**Issue by hanspeter256** [jaredlll08/WaitingTime#11]
Hey, the Waiting Time mod increases so much launching Time...

Could you optimize this..?

**Comment by jaredlll08** [comment]
No way.

**Comment by louino2478** [comment]
I have the same problem
my game without the mods: 3min30s
my game with the mods : 45min
I can send you all my logs if you want to check

**Comment by jaredlll08** [comment]
I have never been able to reproduce, there will be nothing in your log that could help, I hear optifine can cause the issue though, so if you have that, remove it.

At the end of the day, if the mod increases the load time, remove the mod, you don't lose out on anything in game and could probably just open a pong game in your browser while you wait without causing any load time issues.
