### ISSUE TITLE
Game significantly increases load time

### ISSUE THREAD

**Issue by Jemsuper** [jaredlll08/WaitingTime#5]
Based on this post https://old.reddit.com/r/feedthebeast/comments/akiyav/project_ozone_3_waiting_time_pong_mod/

**Comment by jaredlll08** [comment]
I've done some very minor improvements, but I doubt it will do much, if you don't want to use the mod, you can disable it in the forge splash screen (fun fact, the normal forge splash screen causes the game to run slower as well).
